### ISSUE TITLE
NullPointerException during pre-init only in live enviroment

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/Forgescript#2]
For some reason the engine is null. This also only happens with a compiled jar in a user environment, but not dev.

java.lang.NullPointerException
    at org.ame.jsforge.ForgeScript.loadMod(ForgeScript.java:115) ~[ForgeScript.class:?]
    at org.ame.jsforge.ForgeScript.loadAllJSMods(ForgeScript.java:65) ~[ForgeScript.class:?]
    at org.ame.jsforge.ForgeScript.preInit(ForgeScript.java:36) ~[ForgeScript.class:?]
[Removed irrelevant stacktrace]

**Comment by Ameliorate** [comment]
Still happens. See http://paste.ee/p/HszXS
